### ISSUE TITLE
Can you Releases to file.exe?

### ISSUE THREAD

**Issue by nonamebatbai** [style77/rtTranslator#1]
Can you Releases to file.exe?
I don't know how to build it into an .exe file
And can it translate from English to Vietnamese?
please help me

**Comment by style77** [comment]
Hey,
after I finish the first version of app it'll be released as .exe. Right now there are so many things to fix it's not even worth, however you can make an build using pyInstaller or cx_freeze on your own, or just use [Installation guide](https://github.com/style77/rtTranslator?tab=readme-ov-file#installation) and use the development version.

If you want to change language, just head to [config.py](https://github.com/style77/rtTranslator/blob/master/app/config.py) and change `TARGET_LANGUAGE` to desired language.

**Comment by nonamebatbai** [comment]
> Hey, after I finish the first version of app it'll be released as .exe. Right now there are so many things to fix it's not even worth, however you can make an build using pyInstaller or cx_freeze on your own, or just use [Installation guide](https://github.com/style77/rtTranslator?tab=readme-ov-file#installation) and use the development version.
> 
> If you want to change language, just head to [config.py](https://github.com/style77/rtTranslator/blob/master/app/config.py) and change `TARGET_LANGUAGE` to desired language.

Thank you for answering my question
I tried following the Installation Instructions. but not successful
I hope you will release it as an .exe soon

**Comment by style77** [comment]
First version will be probably done in like a week, leave a star so you can get notifcation when I release it 😁.

**Comment by style77** [comment]
@nonamebatbai first release is out! Please tell me if there are any issues with it, don't forget to set up loopback device as shown in README.md.

[v0.0.1](https://github.com/style77/rtTranslator/releases/tag/v0.0.1)
