### ISSUE TITLE
can you help me ?

### ISSUE THREAD

**Issue by nonamebatbai** [style77/rtTranslator#2]
![image](https://github.com/style77/rtTranslator/assets/55612825/0a58c1d7-67c3-4a01-b34a-c3e6510e601e)
Thank you for completing the software
Can you see if I am running the software correctly?
I ran the software but didn't see any audio-to-text translation?
![image](https://github.com/style77/rtTranslator/assets/55612825/70751f80-0609-4290-a0bc-c251cefea6ad)
I followed the instructions but the line "CABLE Output (VB-Audio Virtual Cable)" is red. Can't see the text when the video plays?

**Comment by style77** [comment]
Hey @nonamebatbai,

the red text probably says that there is something wrong with this virtual audio device, it may be broken drivers or something else. 
You can reach out to more experienced people at [VB-audio discord server](https://discord.com/invite/mBvWzeF3a8), they will definitely help u better than me. There is nothing wrong with application, it's just something wrong with this virtual device, I hope they will help you resolve this issue, but unfortunately I'm not able to. Please tell me if they helped you.

You can also compare our settings, mine are:

![image](https://github.com/style77/rtTranslator/assets/36776006/6c868c53-e3fd-4d4f-987d-06ad66ba55fe)
![image](https://github.com/style77/rtTranslator/assets/36776006/18409d56-4aa3-4edb-8982-514e0cb633b2)

**Comment by nonamebatbai** [comment]
![image](https://github.com/style77/rtTranslator/assets/55612825/6d36b836-c803-4b37-8e1d-c5d0d0e73a80)
I have already fixed it.
but I don't see software that translates audio from video to text

**Comment by nonamebatbai** [comment]
![image](https://github.com/style77/rtTranslator/assets/55612825/e316d9a8-5936-4528-91d2-bc0031fcaf53)
it finally worked.
Can you change the font color to black so it's easier to see?
Thank you very much for the software

**Comment by style77** [comment]
Im happy you like it, if you want to change language go to config.json and reload app :).

I’ll add font color change withing menu bar in next release.
